# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

FACEBOOK_APP_KEY: '276641079520830' 
FACEBOOK_APP_SECRET: '89ee20ee54f18673a7aae37c3174c4ff'

S3_BUCKET_NAME: "bucket4head"
AWS_ACCESS_KEY_ID: "AKIAJYV742EBCXJNTDMQ"
AWS_SECRET_ACCESS_KEY: "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"
AWS_REGION: "ap-southeast-1"

BRAINTREE_MERCHANT_ID: 'vdw3k6wfvbtz838x'
BRAINTREE_PUBLIC_KEY: '24t2mcgfghbgyc5f'
BRAINTREE_PRIVATE_KEY: '99a274e46fcfabfe89b63e756c1d36a6'


GMAIL_USERNAME: 'wkitsin94@gmail.com'
GMAIL_PASSWORD: 'kiting88'



